// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PGE.Models;

public partial class Distribuir
{
    public int Id { get; set; }

    public int ProcessoId { get; set; }

    public int ResponsavelAntigoId { get; set; }

    public int ResponsavelNovoId { get; set; }

    public DateOnly? Data { get; set; }

    public virtual Processo Processo { get; set; }

    public virtual Pessoa ResponsavelAntigo { get; set; }

    public virtual Pessoa ResponsavelNovo { get; set; }
}